# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy React site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Build'
        shell: bash
        run: |
          echo "::group::Build"
          npm --prefix ./front ci ./front
          ${{ inputs.build_command }}
          echo "::endgroup::"
      - name: 'upload'
        uses: actions/upload-pages-artifact@v1.0.4
        with: 
          path: 'front/public'

      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ github.token }}

